services:
  django:
    build:
      context: .
      dockerfile: .ci/django/Dockerfile
    depends_on:
      - db
    env_file:
      - ".ci/django/deploy/dev/.env"
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
  db:
    build:
      context: .ci/postgres/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .ci/postgres/deploy/dev/.env
    healthcheck:
      test: pg_isready
