services:
  db:
    build:
      context: .ci/postgres/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .ci/postgres/deploy/dev/.env
    healthcheck:
      test: pg_isready
