# Generated by Django 4.1.7 on 2023-03-09 12:50

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('reservation', '0001_initial'), ('reservation', '0002_remove_reservation_date_range'), ('reservation', '0003_alter_roomreservation_unique_together_and_more')]

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled')], default='PENDING', max_length=30, verbose_name='Статус бронирования')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.reservation', verbose_name='Бронирование')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронирование комнаты',
                'verbose_name_plural': 'Бронирования комнат',
                'unique_together': set(),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ManyToManyField(through='reservation.RoomReservation', to='room.room'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_range',
        ),
        migrations.AddConstraint(
            model_name='roomreservation',
            constraint=models.UniqueConstraint(fields=('reservation', 'room'), name='reservation_room_unique'),
        ),
    ]
