# Generated by Django 4.1.7 on 2023-03-02 15:32
import datetime

import django.contrib.postgres.fields.ranges
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=("2011-11-11","2011-11-12")),
            preserve_default=False,
        ),
    ]
