# Generated by Django 4.1.7 on 2023-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled')], default='PENDING', max_length=30, verbose_name='Статус бронирования'),
        ),
    ]
