# Generated by Django 4.1.7 on 2023-03-01 12:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Время заезда')),
                ('end_date', models.DateField(verbose_name='Время выезда')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(1)], verbose_name='Номер комнаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservationStatus',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled')], default='PENDING', max_length=30, verbose_name='Статус бронирования')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Тип комнаты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.reservation', verbose_name='Бронирование')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.room', verbose_name='Комната')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.roomreservationstatus', verbose_name='Статус бронирования')),
            ],
            options={
                'unique_together': {('reservation', 'room')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.roomtype', verbose_name='Тип комнаты'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ManyToManyField(through='room.RoomReservation', to='room.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'type')},
        ),
    ]
