# Generated by Django 4.1.7 on 2023-03-09 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('room', '0001_initial'), ('room', '0002_alter_room_capacity_alter_room_number')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер комнаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
