# Generated by Django 4.1.7 on 2023-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roomreservation',
            options={'verbose_name': 'Бронирование комнаты', 'verbose_name_plural': 'Бронирования комнат'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Тип комнаты', 'verbose_name_plural': 'Типы комнаты'},
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Одобрено'), ('PENDING', 'Рассматривается'), ('CANCELED', 'Отменено')], default='PENDING', max_length=30, verbose_name='Статус бронирования'),
        ),
        migrations.DeleteModel(
            name='RoomReservationStatus',
        ),
    ]
