# Generated by Django 4.1.7 on 2023-03-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
